[package]
name = "aoc"
version = "0.1.0"
authors = ["Vsevolod Strukchinskii <floatdrop@gmail.com>"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
